import { createClient } from '@supabase/supabase-js';
import { sendEmail, bookingUrl, esc, date, money } from '../../../lib/serverEmail';
const URL='https://gxwemplbykjxhezefykh.supabase.co';
function db(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!k)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.');return createClient(URL,k,{auth:{persistSession:false,autoRefreshToken:false}})}
function token(req){return String(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim()}
export async function POST(req){try{const d=db(),t=token(req);if(!t)return Response.json({success:false,error:'Authentication required.'},{status:401});const{data:u,error:ue}=await d.auth.getUser(t);if(ue||!u?.user)return Response.json({success:false,error:'Invalid login session.'},{status:401});const body=await req.json(),bookingId=String(body.bookingId||'');
const {data:g}=await d.from('guests').select('id,full_name,email,phone').eq('user_id',u.user.id).maybeSingle();if(!g)return Response.json({success:false,error:'Guest account required.'},{status:403});
const {data:b}=await d.from('bookings').select('id,booking_code,property_id,guest_id,check_in,check_out,guests_count,total_amount,final_payable_amount,amount_including_gst').eq('id',bookingId).eq('guest_id',g.id).maybeSingle();if(!b)return Response.json({success:false,error:'Booking not found.'},{status:404});
const {data:p}=await d.from('properties').select('id,name,location_name,area,city,host_id').eq('id',b.property_id).maybeSingle();if(!p?.host_id)return Response.json({success:true,sent:false});
const {data:h}=await d.from('host_profiles').select('id,user_id,full_name,business_name,email').eq('id',p.host_id).maybeSingle();if(!h?.email)return Response.json({success:true,sent:false});
const amount=Number(b.final_payable_amount||b.amount_including_gst||b.total_amount||0);
const r=await sendEmail({to:h.email,subject:`New booking request ${b.booking_code} - ${p.name}`,title:'You have a new booking request',preheader:`${g.full_name||'A guest'} requested ${p.name}`,bodyHtml:`<p style="font-size:14px;line-height:1.65;color:#5d6670">${esc(g.full_name||'A Guest')} has requested <b>${esc(p.name||'your property')}</b>.</p><table style="width:100%;border-collapse:collapse;font-size:13px"><tr><td style="padding:8px 0;color:#77808a">Check-in</td><td style="padding:8px 0;text-align:right;font-weight:700">${date(b.check_in)}</td></tr><tr><td style="padding:8px 0;color:#77808a">Check-out</td><td style="padding:8px 0;text-align:right;font-weight:700">${date(b.check_out)}</td></tr><tr><td style="padding:8px 0;color:#77808a">Guests</td><td style="padding:8px 0;text-align:right;font-weight:700">${Number(b.guests_count||0)}</td></tr><tr><td style="padding:8px 0;color:#77808a">Booking value</td><td style="padding:8px 0;text-align:right;font-weight:700">${money(amount)}</td></tr></table><p style="font-size:12px;color:#7a838c">Approve or decline the request within 24 hours. Guest contact details remain private until payment is completed.</p>`,ctaLabel:'Review booking request',ctaUrl:bookingUrl(`/host/bookings?booking=${b.id}`)});
return Response.json({success:true,sent:r.sent});}catch(e){console.error(e);return Response.json({success:false,error:e?.message||'Unable to send booking email.'},{status:500})}}
