import { createClient } from '@supabase/supabase-js';
const URL='https://gxwemplbykjxhezefykh.supabase.co';
function db(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!k)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.');return createClient(URL,k,{auth:{persistSession:false,autoRefreshToken:false}})}
function token(req){return String(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim()}
async function user(req,d){const t=token(req);if(!t)throw Object.assign(new Error('Authentication required.'),{status:401});const{data,error}=await d.auth.getUser(t);if(error||!data?.user)throw Object.assign(new Error('Invalid login session.'),{status:401});return data.user}
function norm(v=''){return String(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(mr|mrs|ms|miss|dr|shri|smt|kumari)\b/g,' ').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function edit(a,b){const x=norm(a),y=norm(b);if(x===y)return 1;if(!x||!y)return 0;const prev=Array.from({length:y.length+1},(_,i)=>i);for(let i=1;i<=x.length;i++){let diag=prev[0];prev[0]=i;for(let j=1;j<=y.length;j++){const old=prev[j];prev[j]=Math.min(prev[j]+1,prev[j-1]+1,diag+(x[i-1]===y[j-1]?0:1));diag=old}}return 1-prev[y.length]/Math.max(x.length,y.length)}
function nameScore(a,b){const na=norm(a),nb=norm(b);if(!na||!nb)return 0;if(na===nb)return 1;const A=na.split(' ').filter(Boolean),B=nb.split(' ').filter(Boolean),sa=[...A].sort().join(' '),sb=[...B].sort().join(' ');if(sa===sb)return .99;const longA=A.filter(x=>x.length>1),longB=B.filter(x=>x.length>1);const matches=(x,y)=>x===y||(x.length===1&&y.startsWith(x))||(y.length===1&&x.startsWith(y));const aCovered=longA.every(x=>B.some(y=>matches(x,y))),bCovered=longB.every(x=>A.some(y=>matches(x,y)));if((aCovered||bCovered)&&A.some(x=>B.some(y=>matches(x,y))))return .96;const shared=A.filter(x=>B.some(y=>matches(x,y))).length,coverage=shared/Math.max(1,Math.min(A.length,B.length));return Math.max(edit(na,nb),edit(sa,sb),coverage)}
export async function GET(req){try{const d=db(),u=await user(req,d);const{data,error}=await d.from('identity_verifications').select('*').eq('user_id',u.id).order('submitted_at',{ascending:false});if(error)throw error;return Response.json({success:true,items:data||[],mode:'phase1_name_match'})}catch(e){return Response.json({error:e?.message||'Unable to load verification.'},{status:e?.status||500})}}
export async function POST(req){try{const d=db(),u=await user(req,d),fd=await req.formData();const role=String(fd.get('role')||'guest'),docType=String(fd.get('documentType')||''),bookingId=String(fd.get('bookingId')||'').trim()||null,declaredName=String(fd.get('documentName')||'').trim(),file=fd.get('file');if(!['guest','host'].includes(role))return Response.json({error:'Invalid account type.'},{status:400});if(!['pan','aadhaar','passport','driving_licence'].includes(docType))return Response.json({error:'Select a supported ID document.'},{status:400});if(!declaredName)return Response.json({error:'Enter the name exactly as printed on the ID.'},{status:400});if(!file||typeof file.arrayBuffer!=='function')return Response.json({error:'Choose a document file.'},{status:400});if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))return Response.json({error:'Use JPG, PNG, WEBP or PDF.'},{status:400});if(file.size>10*1024*1024)return Response.json({error:'Document must be under 10 MB.'},{status:400});let profile,registeredName='';if(role==='guest'){const{data:g}=await d.from('guests').select('id,full_name').eq('user_id',u.id).maybeSingle();if(!g)throw Object.assign(new Error('Guest profile not found.'),{status:403});profile=g;registeredName=g.full_name||'';if(bookingId){const{data:b}=await d.from('bookings').select('id').eq('id',bookingId).eq('guest_id',g.id).maybeSingle();if(!b)throw Object.assign(new Error('Booking not found.'),{status:403})}}else{const{data:h}=await d.from('host_profiles').select('id,full_name,business_name').eq('user_id',u.id).maybeSingle();if(!h)throw Object.assign(new Error('Host profile not found.'),{status:403});profile=h;registeredName=h.full_name||h.business_name||''}
const score=nameScore(registeredName,declaredName),matched=score>=.86;const ext=(file.name?.split('.').pop()||'dat').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${role}/${u.id}/${Date.now()}-${docType}.${ext}`;const{error:up}=await d.storage.from('identity-documents').upload(path,Buffer.from(await file.arrayBuffer()),{contentType:file.type,upsert:false});if(up)throw up;const status=matched?'verified':'rejected';const row={user_id:u.id,role,guest_id:role==='guest'?profile.id:null,host_id:role==='host'?profile.id:null,booking_id:bookingId,document_type:docType,document_path:path,document_name:file.name||null,registered_name:registeredName,extracted_name:declaredName,name_match_score:Math.round(score*10000)/100,verification_status:status,authenticity_status:'not_checked',provider:'phase1_declared_name_match',rejection_reason:matched?null:'The ID name does not closely match the registered account name.',reviewed_at:new Date().toISOString(),reviewed_by:null};const{data:item,error:ie}=await d.from('identity_verifications').insert(row).select('*').single();if(ie)throw ie;
if(role==='guest'){await d.from('guests').update({identity_verification_status:status,updated_at:new Date().toISOString()}).eq('id',profile.id);if(bookingId)await d.from('bookings').update({verification_status:matched?'completed':'rejected',verification_completed_at:matched?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',bookingId)}else await d.from('host_profiles').update({identity_verification_status:status,updated_at:new Date().toISOString()}).eq('id',profile.id);
try { await d.from('notifications').insert({recipient_type:role,recipient_user_id:u.id,recipient_guest_id:role==='guest'?profile.id:null,host_id:role==='host'?profile.id:null,booking_id:bookingId,type:'identity_name_match',title:matched?'Name matched successfully':'ID name does not match',body:matched?'Your registered name matches the name you entered from your ID. Phase 1 verification is complete.':'The ID name you entered does not match your registered account name closely enough. Check the spelling or update your account name and try again.',priority:matched?'normal':'important',action_url:role==='guest'?'/account/verification':'/host/verification',email_status:'skipped'}); } catch {}
return Response.json({success:true,item,matched,score:Math.round(score*100),mode:'phase1_name_match',note:'Name match only. Document authenticity is not verified in Phase 1.'});}catch(e){return Response.json({error:e?.message||'Unable to submit verification.'},{status:e?.status||500})}}
