'use client';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const s=createClient('https://gxwemplbykjxhezefykh.supabase.co','sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS');
const MAP=[['/admin/properties','properties'],['/admin/bookings','bookings'],['/admin/hosts','hosts'],['/admin/guests','guests'],['/admin/referrals','referrals'],['/admin/payouts','payouts'],['/admin/payment-holds','payment-holds']];
async function fetchRows(dataset){const{data:{session}}=await s.auth.getSession();if(!session?.access_token)throw new Error('Admin login required.');const r=await fetch(`/api/admin/reports?dataset=${encodeURIComponent(dataset)}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Unable to generate report.');return j}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function table(data){const rows=data.rows||[],keys=rows[0]?Object.keys(rows[0]):[];return `<table border="1"><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
export default function AdminExportTools(){const path=usePathname(),[busy,setBusy]=useState(''),[err,setErr]=useState('');if(path==='/admin/reports'||path==='/admin/login')return null;const dataset=MAP.find(([p])=>path===p||path?.startsWith(`${p}/`))?.[1];if(!dataset)return null;async function excel(){try{setBusy('excel');setErr('');const d=await fetchRows(dataset),html=`<html><head><meta charset="utf-8"></head><body><h2>${esc(d.title)}</h2>${table(d)}</body></html>`,blob=new Blob([html],{type:'application/vnd.ms-excel'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`NightOutStays-${dataset}-${new Date().toISOString().slice(0,10)}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){setErr(e.message)}finally{setBusy('')}}async function pdf(){try{setBusy('pdf');setErr('');const d=await fetchRows(dataset),w=window.open('','_blank');if(!w)throw new Error('Allow pop-ups to export PDF.');w.document.write(`<html><head><title>${esc(d.title)}</title><style>body{font:11px Arial;padding:24px;color:#303a44}h1{font-size:20px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #d9dee4;padding:6px;text-align:left}th{background:#f1f3f5}@page{size:landscape;margin:10mm}</style></head><body><h1>NightOutStays · ${esc(d.title)}</h1><p>Generated ${new Date(d.generatedAt).toLocaleString('en-IN')}</p>${table(d)}<script>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}catch(e){setErr(e.message)}finally{setBusy('')}}return <div className="adminExportBar"><span>Data export</span><button onClick={excel} disabled={!!busy}>{busy==='excel'?'Preparing…':'Download Excel'}</button><button onClick={pdf} disabled={!!busy}>{busy==='pdf'?'Preparing…':'Download PDF'}</button>{err&&<em>{err}</em>}<style jsx>{`.adminExportBar{max-width:1500px;margin:12px auto 0;padding:0 24px;display:flex;justify-content:flex-end;align-items:center;gap:7px;color:#69737d;font:800 10px Arial}.adminExportBar button{border:1px solid #dce2e7;background:#fff;color:#303a44;border-radius:999px;padding:8px 11px;font-size:9px;font-weight:900;cursor:pointer}.adminExportBar button:last-of-type{background:#f00078;color:#fff;border-color:#f00078}.adminExportBar em{font-style:normal;color:#b42318}@media(max-width:600px){.adminExportBar{padding:0 12px;justify-content:flex-start;overflow:auto}.adminExportBar span{display:none}}`}</style></div>}
