'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@supabase/supabase-js';
const s=createClient('https://gxwemplbykjxhezefykh.supabase.co','sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS');
export default function AdminDashboard(){const[d,setD]=useState({hosts:0,properties:0,guests:0,bookings:0,pendingHosts:0,pendingProperties:0,paid:0}),[loading,setLoading]=useState(true),[err,setErr]=useState('');
async function load(){setLoading(true);setErr('');try{const{data:{session}}=await s.auth.getSession();if(!session){location.href='/admin/login';return}const [h,p,g,b]=await Promise.all([s.from('host_profiles').select('id,status',{count:'exact'}),s.from('properties').select('id,moderation_status',{count:'exact'}),s.from('guests').select('id',{count:'exact'}),s.from('bookings').select('id,payment_status',{count:'exact'})]);for(const x of[h,p,g,b])if(x.error)throw x.error;setD({hosts:h.count||0,properties:p.count||0,guests:g.count||0,bookings:b.count||0,pendingHosts:(h.data||[]).filter(x=>['pending','pending_review'].includes(String(x.status))).length,pendingProperties:(p.data||[]).filter(x=>String(x.moderation_status)==='pending_review').length,paid:(b.data||[]).filter(x=>String(x.payment_status).toLowerCase()==='paid').length})}catch(e){setErr(e.message||'Unable to load dashboard.')}finally{setLoading(false)}}useEffect(()=>{load()},[]);
return <main className="dash"><header><div><small>ADMIN CONTROL CENTER</small><h1>Dashboard</h1><p>NightOutStays operations at a glance.</p></div><button onClick={load}>Refresh</button></header>{err&&<div className="err">{err}</div>}<section className="stats"><Card n={d.hosts} t="Hosts"/><Card n={d.properties} t="Properties"/><Card n={d.guests} t="Guests"/><Card n={d.bookings} t="Bookings"/><Card n={d.pendingHosts} t="Host Requests" hot/><Card n={d.pendingProperties} t="Property Reviews" hot/><Card n={d.paid} t="Paid Bookings"/></section><section className="quick"><h2>Operations</h2><div><Link href="/admin/hosts">Manage Hosts</Link><Link href="/admin/properties">Manage Properties</Link><Link href="/admin/bookings">Bookings</Link><Link href="/admin/reports">Reports</Link><Link href="/admin/system-health">System Health</Link><Link href="/admin/settings">Settings</Link></div></section>{loading&&<p className="muted">Refreshing dashboard…</p>}<style jsx>{`.dash{max-width:1450px;margin:auto;padding:28px 24px 70px;color:#303a44}header{display:flex;justify-content:space-between;gap:20px;align-items:center}small{font-weight:900;color:#f00078}h1{font-size:38px;margin:5px 0}p{color:#71808c}button{border:1px solid #d8dee5;background:#fff;border-radius:10px;padding:10px 15px;font-weight:900}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin:22px 0}.quick{background:#fff;border:1px solid #e0e5ea;border-radius:18px;padding:20px}.quick div{display:flex;gap:9px;flex-wrap:wrap}.quick a{padding:10px 14px;border-radius:999px;text-decoration:none;color:#303a44;border:1px solid #dce2e7;font-weight:900}.err{background:#fff0f0;color:#a40000;padding:12px;border-radius:10px}@media(max-width:800px){.stats{grid-template-columns:1fr 1fr}}`}</style></main>}
function Card({n,t,hot}){return <article className={hot?'card hot':'card'}><b>{n}</b><span>{t}</span><style jsx>{`.card{background:#fff;border:1px solid #e0e5ea;border-radius:17px;padding:18px;display:grid;gap:4px}.card b{font-size:29px}.card span{font-size:11px;font-weight:900;color:#75808a}.hot{border-color:#f7b5d4}.hot b{color:#f00078}`}</style></article>}
