'use client';
import { usePathname } from 'next/navigation';
export default function SiteFooter(){
  const pathname=usePathname();
  if(pathname?.startsWith('/admin')||pathname?.startsWith('/host')||pathname?.startsWith('/account')) return null;
  return <footer className="nosFooter"><div className="footerGrid"><div className="footerBrand"><strong>NightOut<span>Stays</span></strong><p>Short stays, weekend escapes and memorable spaces across India.</p></div><div><b>Explore</b><a href="/">Browse Stays</a><a href="/#all-stays">Popular Stays</a><a href="/host/register">List Your Property</a></div><div><b>Guests</b><a href="/account/bookings">My Bookings</a><a href="/account/favorites">Favorites</a><a href="/account/messages">Messages</a></div><div><b>Company</b><a href="/account/help">Help Center</a><a href="/login">Login</a><a href="/host/register">Become a Host</a></div></div><div className="footerBottom"><span>© 2026 NightOutStays</span><span>Secure payments · Verified hosts · Transparent pricing</span></div><style jsx global>{`
  .nosFooter{margin-top:46px;background:#1f2933;color:#fff;font-family:Arial,sans-serif}.footerGrid{max-width:1450px;margin:auto;padding:44px 28px 34px;display:grid;grid-template-columns:1.5fr repeat(3,1fr);gap:34px}.footerBrand strong{font-size:28px;letter-spacing:-1px}.footerBrand strong span{color:#f00078}.footerBrand p{max-width:360px;line-height:1.6;color:#c9d0d8;font-size:13px}.footerGrid>div:not(.footerBrand){display:flex;flex-direction:column;gap:10px}.footerGrid b{font-size:13px;margin-bottom:4px}.footerGrid a{color:#c9d0d8;text-decoration:none;font-size:12px}.footerGrid a:hover{color:#fff}.footerBottom{border-top:1px solid rgba(255,255,255,.1);max-width:1450px;margin:auto;padding:18px 28px 24px;display:flex;justify-content:space-between;gap:20px;color:#aeb8c2;font-size:11px}@media(max-width:760px){.footerGrid{grid-template-columns:1fr 1fr;padding:32px 18px}.footerBrand{grid-column:1/-1}.footerBottom{padding:16px 18px 22px;flex-direction:column;gap:6px}}
`}</style></footer>
}
