"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const sb=createClient("https://gxwemplbykjxhezefykh.supabase.co","sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS");
const dt=v=>new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
export default function AdminNotifications(){
 const [data,setData]=useState(null),[filter,setFilter]=useState("unread"),[error,setError]=useState("");
 async function token(){const {data}=await sb.auth.getSession();return data?.session?.access_token}
 async function load(){try{const t=await token();if(!t){location.href="/admin/login";return}const r=await fetch("/api/admin/notifications",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}catch(e){setError(e.message)}}
 async function act(action,id){const t=await token();await fetch("/api/admin/notifications",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({action,id})});load()}
 useEffect(()=>{load();const x=setInterval(load,30000);return()=>clearInterval(x)},[]);
 const rows=useMemo(()=>{let a=data?.notifications||[];if(filter==="unread")a=a.filter(x=>!x.is_read);else if(["urgent","important","normal"].includes(filter))a=a.filter(x=>x.priority===filter);return a},[data,filter]);
 return <main style={s.page}><div style={s.head}><div><h1 style={s.h1}>Notifications</h1><p style={s.sub}>Priority alerts and action-required events for NightOutStays Admin.</p></div><div style={s.actions}><a href="/admin/support" style={s.linkBtn}>Support Center</a><button style={s.btn} onClick={()=>act("read_all")}>Mark all read</button></div></div>
 {error&&<div style={s.err}>{error}</div>}
 <div style={s.cards}><Card l="Unread" v={data?.summary?.unread||0}/><Card l="Urgent" v={data?.summary?.urgent||0}/><Card l="Important" v={data?.summary?.important||0}/><Card l="All" v={data?.summary?.total||0}/></div>
 <div style={s.filters}>{[["unread","Unread"],["urgent","Urgent"],["important","Important"],["normal","Normal"],["all","All"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} style={{...s.filter,...(filter===v?s.filterOn:{})}}>{l}</button>)}</div>
 <section style={s.panel}>{rows.length?rows.map(n=><article key={n.id} style={{...s.note,opacity:n.is_read?.72:1,borderLeft:`5px solid ${n.priority==="urgent"?"#b91c1c":n.priority==="important"?"#b45309":"#315b85"}`}}>
   <div style={s.noteTop}><div><span style={s.priority}>{n.priority.toUpperCase()}</span><h3 style={s.h3}>{n.title}</h3></div><small>{dt(n.created_at)}</small></div><p style={s.body}>{n.body}</p>
   <div style={s.noteActions}>{n.action_url&&<a href={n.action_url} onClick={()=>!n.is_read&&act("read",n.id)} style={s.open}>Open</a>}<button style={s.smallBtn} onClick={()=>act(n.is_read?"unread":"read",n.id)}>{n.is_read?"Mark unread":"Mark read"}</button></div>
 </article>):<div style={s.empty}>No notifications in this filter.</div>}</section>
 </main>}
function Card({l,v}){return <div style={s.card}><span>{l}</span><strong>{v}</strong></div>}
const s={page:{maxWidth:1350,margin:"auto",padding:28,background:"#f6f8fb",minHeight:"100vh",fontFamily:"Arial",color:"#17324d"},head:{display:"flex",justifyContent:"space-between",gap:18,alignItems:"center"},h1:{fontSize:34,margin:0,color:"#082f5a"},sub:{color:"#6b7c8e"},actions:{display:"flex",gap:8},btn:{background:"#082f5a",color:"#fff",border:0,borderRadius:9,padding:"10px 14px",fontWeight:700},linkBtn:{background:"#fff",color:"#082f5a",border:"1px solid #cbd5e1",borderRadius:9,padding:"10px 14px",fontWeight:700,textDecoration:"none"},cards:{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,margin:"20px 0"},card:{background:"#fff",border:"1px solid #dfe6ee",borderRadius:14,padding:17},filters:{display:"flex",gap:8,flexWrap:"wrap",marginBottom:14},filter:{background:"#fff",border:"1px solid #ccd7e2",padding:"9px 12px",borderRadius:9,fontWeight:700,color:"#315b85"},filterOn:{background:"#082f5a",color:"#fff"},panel:{background:"#fff",border:"1px solid #e1e7ee",borderRadius:15,padding:14},note:{padding:"16px 18px",borderBottom:"1px solid #edf1f4",background:"#fff"},noteTop:{display:"flex",justifyContent:"space-between",gap:12},priority:{fontSize:10,fontWeight:900,color:"#63788d"},h3:{margin:"5px 0 0",color:"#082f5a"},body:{color:"#4f6478",lineHeight:1.5},noteActions:{display:"flex",gap:8},open:{background:"#082f5a",color:"#fff",padding:"8px 11px",borderRadius:8,textDecoration:"none",fontWeight:700},smallBtn:{background:"#fff",border:"1px solid #cbd5e1",borderRadius:8,padding:"8px 11px",fontWeight:700,color:"#315b85"},err:{background:"#fff1f2",color:"#991b1b",padding:12,borderRadius:10,marginTop:14},empty:{padding:35,textAlign:"center",color:"#728397"}};
