'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient('https://gxwemplbykjxhezefykh.supabase.co','sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS');
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(v||0));
function loadRazorpay(){if(window.Razorpay)return Promise.resolve(true);return new Promise(r=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>r(true);s.onerror=()=>r(false);document.body.appendChild(s)})}
export default function PayPage(){const {code}=useParams();const router=useRouter();const [data,setData]=useState(null),[loading,setLoading]=useState(true),[paying,setPaying]=useState(false),[error,setError]=useState('');
 async function session(){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token){router.replace(`/login?redirect=/booking/${code}/pay`);return null}return session}
 async function load(){try{setLoading(true);const s=await session();if(!s)return;const r=await fetch(`/api/bookings/payment-details?code=${encodeURIComponent(code)}`,{headers:{Authorization:`Bearer ${s.access_token}`},cache:'no-store'}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Unable to load booking.');setData(j)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[code]);
 async function pay(){if(paying||!data)return;setPaying(true);setError('');try{const s=await session();if(!s)return;const ok=await loadRazorpay();if(!ok)throw new Error('Unable to load secure payment window.');const r=await fetch('/api/razorpay/create-order',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({bookingCode:code})}),o=await r.json();if(!r.ok||!o.success)throw new Error(o.error||'Unable to create payment order.');new window.Razorpay({key:o.keyId,amount:o.amount,currency:o.currency,name:'NightOutStays',description:`Booking ${code}`,order_id:o.orderId,prefill:{name:data.guest?.full_name||'',email:data.guest?.email||'',contact:data.guest?.phone||''},theme:{color:'#f4007d'},handler:async payment=>{const vr=await fetch('/api/razorpay/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingCode:code,...payment})}),v=await vr.json();if(!vr.ok||!v.success)throw new Error(v.error||'Payment verification failed.');router.replace('/account/bookings?payment=success');router.refresh()},modal:{ondismiss:()=>setPaying(false)}}).open()}catch(e){setError(e.message);setPaying(false)}}
 if(loading)return <main className="payPage"><div className="payCard">Loading secure payment…</div><Style/></main>;if(error&&!data)return <main className="payPage"><div className="payCard"><h1>Payment</h1><div className="err">{error}</div><a href="/account/bookings">Back to My Bookings</a></div><Style/></main>;const b=data.booking,p=data.property;const amount=Number(b.final_payable_amount||b.amount_including_gst||b.total_amount||0);const expired=b.payment_due_at&&Date.now()>new Date(b.payment_due_at).getTime();return <main className="payPage"><div className="payCard"><div className="brand">NightOut<span>Stays</span></div><div className="payGrid"><div>{p?.cover_image&&<img src={p.cover_image} alt=""/>}<h1>{p?.name||'Your stay'}</h1><p>{p?.location_name||p?.area||p?.city}</p><div className="dates"><span>Check-in<b>{b.check_in}</b></span><span>Check-out<b>{b.check_out}</b></span><span>Guests<b>{b.guests_count}</b></span></div></div><aside><small>BOOKING {b.booking_code}</small><h2>{money(amount)}</h2><p>Final amount payable including applicable GST.</p>{b.offer_status==='accepted'&&<div className="offer">Special offer accepted</div>}{b.payment_due_at&&<div className="due">Pay before {new Date(b.payment_due_at).toLocaleString('en-IN')}</div>}{error&&<div className="err">{error}</div>}<button disabled={paying||expired||b.payment_status==='paid'||b.host_decision!=='approved'} onClick={pay}>{b.payment_status==='paid'?'Already Paid':expired?'Payment Window Expired':paying?'Opening Payment…':'Pay Securely Now'}</button><a href="/account/bookings">← Back to My Bookings</a></aside></div></div><Style/></main>}
function Style(){return <style jsx global>{`.payPage{min-height:100vh;background:linear-gradient(145deg,#f8fbff,#fff0f7);padding:42px 18px;color:#10243a}.payCard{max-width:980px;margin:auto;background:#fff;border:1px solid #e5eaf1;border-radius:24px;padding:26px;box-shadow:0 20px 60px rgba(15,23,42,.12)}.brand{font-size:24px;font-weight:950;color:#082f5a;margin-bottom:22px}.brand span{color:#f4007d}.payGrid{display:grid;grid-template-columns:1.35fr .75fr;gap:24px}.payGrid img{width:100%;height:300px;object-fit:cover;border-radius:18px}.payGrid h1{font-size:27px;margin:15px 0 4px}.payGrid p{color:#64748b}.dates{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.dates span{background:#f8fafc;border:1px solid #e7edf3;border-radius:12px;padding:12px;font-size:11px;color:#64748b}.dates b{display:block;color:#10243a;margin-top:4px}.payGrid aside{border:1px solid #e1e8ef;border-radius:18px;padding:20px;height:max-content}.payGrid aside small{font-weight:900;color:#64748b}.payGrid aside h2{font-size:34px;color:#082f5a;margin:12px 0}.offer{background:#ecfdf3;color:#08783e;padding:10px;border-radius:10px;font-weight:800;margin:12px 0}.due{background:#fff8e7;color:#8a5d00;padding:10px;border-radius:10px;font-size:12px;margin:12px 0}.err{background:#fff1f2;color:#a61b2b;padding:10px;border-radius:10px;margin:12px 0}.payGrid aside button{width:100%;border:0;background:linear-gradient(135deg,#f4007d,#d4006c);color:#fff;border-radius:12px;padding:14px;font-weight:950;font-size:15px;cursor:pointer}.payGrid aside button:disabled{opacity:.45;cursor:not-allowed}.payGrid aside a{display:block;text-align:center;margin-top:13px;text-decoration:none;color:#0b5bd3;font-weight:800;font-size:12px}@media(max-width:720px){.payPage{padding:18px 10px}.payCard{padding:14px;border-radius:16px}.payGrid{grid-template-columns:1fr}.payGrid img{height:210px}.dates{grid-template-columns:1fr 1fr 1fr}.payGrid aside h2{font-size:30px}}`}</style>}
