\'use client\';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { usePathname,useRouter } from 'next/navigation';
import { createClient } from '@supabase/supabase-js';
const supabase=createClient('https://gxwemplbykjxhezefykh.supabase.co','sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS');
const ITEMS=[{label:'Browse Stays',href:'/',icon:'⌂',key:''},{label:'My Bookings',href:'/account/bookings',icon:'▣',key:'bookings'},{label:'Messages',href:'/account/messages',icon:'▭',key:'messages'},{label:'Notifications',href:'/account/notifications',icon:'◈',key:'notifications'},{label:'Reviews',href:'/account/reviews',icon:'★',key:''},{label:'Support',href:'/account/help',icon:'?',key:''},{label:'Profile',href:'/account/profile',icon:'♙',key:''}];
export default function GuestNav({guest}){const pathname=usePathname();const router=useRouter();const [counts,setCounts]=useState({messages:0,notifications:0,bookings:0});useEffect(()=>{let live=true;async function load(){try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return;const r=await fetch('/api/portal/summary?portal=guest',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const j=await r.json();if(live&&j.success)setCounts(j)}catch{}}load();const t=setInterval(load,5000);const vis=()=>{if(document.visibilityState==='visible')load()};window.addEventListener('focus',load);document.addEventListener('visibilitychange',vis);return()=>{live=false;clearInterval(t);window.removeEventListener('focus',load);document.removeEventListener('visibilitychange',vis)}},[]);const active=h=>h==='/'?pathname==='/':pathname===h||pathname?.startsWith(`${h}/`);async function logout(){await supabase.auth.signOut();router.replace('/login');router.refresh()}const name=guest?.full_name||'Guest';return <><div className="portalNavRoot"><div className="portalMobileBrand"><strong>NightOutStays</strong><span>Guest Portal</span></div><div className="portalMenuRow"><div className="portalMenuGrid">{ITEMS.map(i=>{const n=Number(counts[i.key]||0);return <Link key={i.href} href={i.href} className={active(i.href)?'portalItem active':'portalItem'}><span className="portalIconWrap"><span className="portalIcon">{i.icon}</span>{n>0&&<span className="portalBadge">{n>99?'99+':n}</span>}</span><span className="portalLabel">{i.label}</span></Link>})}</div></div><div className="portalDetails"><div className="portalIdentity"><span className="portalRole">GUEST</span><div className="portalWho"><strong>{name}</strong><span>Guest Account</span></div></div><div className="portalActions"><Link href="/" className="portalBtn">↗ Browse Stays</Link><button className="portalBtn" onClick={logout}>Logout</button></div></div></div><Styles/></>}
function Styles(){return <style jsx global>{`
      .portalNavRoot,.portalNavRoot *{box-sizing:border-box}.portalNavRoot{width:100%;background:#fff;border-bottom:1px solid #dfe5ec;position:relative;z-index:1000;font-family:Arial,sans-serif}.portalMenuRow{background:#082f5a;width:100%}.portalMenuGrid{display:grid;width:100%;background:#082f5a}.portalItem{position:relative;min-width:0;min-height:68px;padding:8px 4px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;color:#fff!important;text-decoration:none!important}.portalItem:hover{background:rgba(255,255,255,.08)}.portalItem.active{background:#35618c}.portalItem.active:after{content:'';position:absolute;left:22%;right:22%;bottom:0;height:4px;border-radius:4px 4px 0 0;background:#fff}.portalIconWrap{position:relative;display:inline-flex;align-items:center;justify-content:center}.portalIcon{font-size:16px;line-height:1}.portalBadge{position:absolute;top:-9px;right:-13px;min-width:18px;height:18px;padding:0 5px;border-radius:999px;background:#e11d48;color:#fff;font-size:10px;font-weight:900;display:inline-flex;align-items:center;justify-content:center;border:2px solid #082f5a}.portalLabel{font-size:9px;line-height:1.1;text-align:center;font-weight:900}.portalDetails{min-height:58px;display:flex;align-items:center;justify-content:space-between;gap:16px;width:calc(100% - 48px);max-width:1500px;margin:0 auto}.portalIdentity{display:flex;align-items:center;gap:12px;min-width:0}.portalRole{background:#082f5a;color:#fff;border-radius:999px;padding:6px 10px;font-size:9px;font-weight:900;letter-spacing:.5px;white-space:nowrap}.portalWho{display:flex;flex-direction:column;min-width:0}.portalWho strong{font-size:13px;color:#101828;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.portalWho span{font-size:10px;color:#667085;margin-top:2px}.portalActions{display:flex;gap:8px}.portalBtn{min-height:34px;padding:0 12px;border:1px solid #ccd6e1;border-radius:8px;background:#fff;color:#17324d;text-decoration:none;font-size:10px;font-weight:900;display:inline-flex;align-items:center;justify-content:center;cursor:pointer}.portalMobileBrand{display:none}.portalScrollHint{display:none}
      @media(max-width:900px){.portalMenuGrid{display:flex!important;overflow-x:auto;overflow-y:hidden;scrollbar-width:none;-webkit-overflow-scrolling:touch;scroll-snap-type:x proximity}.portalMenuGrid::-webkit-scrollbar{display:none}.portalItem{flex:0 0 88px;min-height:62px;scroll-snap-align:start}.portalDetails{width:calc(100% - 24px);min-height:54px}.portalLabel{font-size:8.5px}.portalScrollHint{display:block;position:absolute;right:5px;top:21px;color:rgba(255,255,255,.65);font-size:11px;pointer-events:none}.portalActions .portalBtn:first-child{display:none}}
      @media(max-width:560px){.portalNavRoot{position:sticky;top:0}.portalMobileBrand{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;background:#fff}.portalMobileBrand strong{font-size:20px;color:#0b579e}.portalMobileBrand span{font-size:10px;color:#667085;font-weight:800}.portalDetails{padding:7px 0;min-height:48px}.portalWho strong{font-size:12px}.portalWho span{font-size:9px}.portalRole{font-size:8px;padding:5px 8px}.portalBtn{min-height:32px;padding:0 10px;font-size:9px}.portalItem{flex-basis:76px;min-height:58px}.portalIcon{font-size:15px}.portalLabel{font-size:8px}.portalBadge{top:-8px;right:-12px;min-width:17px;height:17px;font-size:9px}.portalMenuRow{box-shadow:0 2px 10px rgba(8,47,90,.12)}}
`}</style>}
