'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient('https://gxwemplbykjxhezefykh.supabase.co','sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS');
const ITEMS=[{label:'Browse Stays',href:'/',icon:'⌂',key:''},{label:'Favorites',href:'/account/favorites',icon:'♥',key:''},{label:'My Bookings',href:'/account/bookings',icon:'▣',key:'bookings'},{label:'Messages',href:'/account/messages',icon:'✉',key:'messages'},{label:'Notifications',href:'/account/notifications',icon:'◇',key:'notifications'},{label:'Reviews',href:'/account/reviews',icon:'★',key:''},{label:'Referrals',href:'/account/referrals',icon:'⇄',key:''},{label:'Support',href:'/account/help',icon:'?',key:''},{label:'Profile',href:'/account/profile',icon:'♙',key:''}];
export default function GuestNav({guest}){const pathname=usePathname(),router=useRouter(),[counts,setCounts]=useState({messages:0,notifications:0,bookings:0});useEffect(()=>{let live=true,timer;async function load(){try{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return;const r=await fetch('/api/portal/summary?portal=guest',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'}),j=await r.json();if(live&&j.success)setCounts(j)}catch{}}const refresh=()=>{clearTimeout(timer);timer=setTimeout(load,120)};load();const ch=supabase.channel('guest-nav-live-v3').on('postgres_changes',{event:'*',schema:'public',table:'booking_messages'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'bookings'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'notifications'},refresh).subscribe();const focus=()=>load();window.addEventListener('focus',focus);return()=>{live=false;clearTimeout(timer);window.removeEventListener('focus',focus);supabase.removeChannel(ch)}},[]);const active=h=>h==='/'?pathname==='/':pathname===h||pathname?.startsWith(`${h}/`);async function logout(){await supabase.auth.signOut();router.replace('/login');router.refresh()}return <><div className="guestNav"><div className="guestNavTop"><Link href="/" className="guestBrand">NightOut<span>Stays</span></Link><div className="guestIdentity"><span className="guestRole">GUEST</span><strong>{guest?.full_name||'Guest'}</strong><button onClick={logout}>Logout</button></div></div><div className="guestNavScroll">{ITEMS.map(i=>{const n=Number(counts[i.key]||0);return <Link key={i.href} href={i.href} className={active(i.href)?'guestNavItem active':'guestNavItem'}><span className="guestIcon">{i.icon}{n>0&&<b>{n>99?'99+':n}</b>}</span><span>{i.label}</span></Link>})}</div></div><style jsx global>{`
.guestNav{background:#fff;border-bottom:1px solid #e4e8ec;position:relative;z-index:1100;font-family:Arial,sans-serif}.guestNavTop{max-width:1450px;margin:auto;min-height:58px;padding:0 24px;display:flex;align-items:center;justify-content:space-between}.guestBrand{text-decoration:none;color:#303a44;font-weight:950;font-size:22px;letter-spacing:-.8px}.guestBrand span{color:#f00078}.guestIdentity{display:flex;align-items:center;gap:9px;color:#4d5863}.guestIdentity strong{font-size:12px}.guestIdentity button{border:1px solid #dce1e6;background:#fff;color:#56616c;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:900;cursor:pointer}.guestRole{background:#303a44;color:#fff;border-radius:999px;padding:5px 8px;font-size:8px;font-weight:900}.guestNavScroll{display:flex;justify-content:center;background:#303a44;overflow-x:auto;scrollbar-width:none}.guestNavScroll::-webkit-scrollbar{display:none}.guestNavItem{position:relative;min-width:100px;min-height:58px;padding:7px 10px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;text-decoration:none;color:#e9edf1;font-size:9px;font-weight:900;white-space:nowrap}.guestNavItem:hover{background:#3a4651}.guestNavItem.active{background:#46525d}.guestNavItem.active:after{content:'';position:absolute;bottom:0;left:25%;right:25%;height:4px;border-radius:5px 5px 0 0;background:#f00078}.guestIcon{position:relative;font-size:15px}.guestIcon b{position:absolute;left:10px;top:-9px;min-width:17px;height:17px;padding:0 4px;border-radius:999px;background:#f00078;color:#fff;border:2px solid #303a44;display:flex;align-items:center;justify-content:center;font-size:8px}@media(max-width:800px){.guestNavScroll{justify-content:flex-start}.guestNavItem{min-width:82px}.guestNavTop{padding:0 14px}.guestBrand{font-size:20px}.guestIdentity strong{display:none}}@media(max-width:500px){.guestIdentity .guestRole{display:none}.guestNavItem{min-width:74px;font-size:8px}.guestNavTop{min-height:52px}}
`}</style></>}
