'use client';
import {useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const s=createClient('https://gxwemplbykjxhezefykh.supabase.co','sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS');
const SETS=[['properties','Property Data'],['bookings','Booking Data'],['hosts','Host Data'],['guests','Guest Data'],['referrals','Referral Data'],['payouts','Payout Data'],['payment-holds','Payment Hold Data']];
async function load(dataset){const{data:{session}}=await s.auth.getSession();if(!session?.access_token)throw new Error('Admin login required.');const r=await fetch(`/api/admin/reports?dataset=${dataset}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Unable to load report.');return j}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function htmlTable(d){const rows=d.rows||[],keys=rows[0]?Object.keys(rows[0]):[];return `<table border="1"><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
export default function Reports(){const[busy,setBusy]=useState(''),[error,setError]=useState('');async function excel(ds){try{setBusy(ds+'e');setError('');const d=await load(ds),blob=new Blob([`<html><meta charset="utf-8"><body><h2>NightOutStays · ${esc(d.title)}</h2>${htmlTable(d)}</body></html>`],{type:'application/vnd.ms-excel'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`NightOutStays-${ds}-${new Date().toISOString().slice(0,10)}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}catch(e){setError(e.message)}finally{setBusy('')}}async function pdf(ds){try{setBusy(ds+'p');setError('');const d=await load(ds),w=window.open('','_blank');if(!w)throw new Error('Allow pop-ups for PDF export.');w.document.write(`<html><head><title>${esc(d.title)}</title><style>body{font:11px Arial;padding:24px;color:#303a44}table{border-collapse:collapse;width:100%}th,td{border:1px solid #d9dee4;padding:6px;text-align:left}th{background:#f1f3f5}@page{size:landscape;margin:10mm}</style></head><body><h1>NightOutStays · ${esc(d.title)}</h1>${htmlTable(d)}<script>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}catch(e){setError(e.message)}finally{setBusy('')}}return <main className="rp"><div className="head"><span>ADMIN REPORTS</span><h1>Reports & Downloads</h1><p>Download operational data as Excel or print/save as PDF.</p></div>{error&&<div className="err">{error}</div>}<div className="grid">{SETS.map(([ds,label])=><article key={ds}><div><small>REPORT</small><h2>{label}</h2><p>{description(ds)}</p></div><div><button onClick={()=>excel(ds)} disabled={!!busy}>{busy===ds+'e'?'Preparing…':'Excel'}</button><button className="pink" onClick={()=>pdf(ds)} disabled={!!busy}>{busy===ds+'p'?'Preparing…':'PDF'}</button></div></article>)}</div><style jsx>{`.rp{max-width:1300px;margin:0 auto;padding:28px 22px 60px;color:#303a44}.head span{color:#f00078;font-size:10px;font-weight:950;letter-spacing:1px}.head h1{font-size:34px;margin:4px 0}.head p{color:#727c86}.err{background:#fff0f0;padding:12px;border-radius:12px;margin:15px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin-top:22px}.grid article{background:#fff;border:1px solid #e1e6ea;border-radius:18px;padding:18px;display:flex;justify-content:space-between;gap:14px;flex-direction:column;min-height:170px}.grid small{color:#f00078;font-size:9px;font-weight:950}.grid h2{font-size:18px;margin:5px 0}.grid p{font-size:11px;color:#77818b;line-height:1.5}.grid article>div:last-child{display:flex;gap:7px}.grid button{border:1px solid #dce2e7;background:#fff;color:#303a44;border-radius:999px;padding:9px 13px;font-size:10px;font-weight:900}.grid .pink{background:#f00078;border-color:#f00078;color:#fff}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.grid{grid-template-columns:1fr}.rp{padding:20px 12px}}`}</style></main>}
function description(ds){return {properties:'Property, Host, city, rates, status and occupancy data.',bookings:'Booking, property, Host, Guest, stay, status and payment data.',hosts:'Host contact, verification status and property counts.',guests:'Guest contact, account and identity status.',referrals:'Referral codes, referrers, referred users and qualification.',payouts:'Settlement, deductions, net payouts and transfer status.','payment-holds':'Current payment holds with Host, property and hold reason.'}[ds]||''}
