import { createClient } from '@supabase/supabase-js';
const URL='https://gxwemplbykjxhezefykh.supabase.co';
function db(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!k)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.');return createClient(URL,k,{auth:{persistSession:false,autoRefreshToken:false}})}
function bearer(req){return String(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim()}
async function current(req,d){const t=bearer(req);if(!t)throw Object.assign(new Error('Authentication required.'),{status:401});const{data:u,error}=await d.auth.getUser(t);if(error||!u?.user)throw Object.assign(new Error('Invalid login session.'),{status:401});const [{data:g},{data:h}]=await Promise.all([d.from('guests').select('id,user_id,full_name,phone,email').eq('user_id',u.user.id).maybeSingle(),d.from('host_profiles').select('id,user_id,full_name,business_name,phone,email,status').eq('user_id',u.user.id).maybeSingle()]);const role=h?'host':g?'guest':null;if(!role)throw Object.assign(new Error('Guest or Host account required.'),{status:403});return{user:u.user,role,profile:role==='host'?h:g}}
function codeFor(role,userId){return `${role==='host'?'HOST':'GUEST'}-${String(userId).replace(/-/g,'').slice(0,8).toUpperCase()}`}
async function ensureCode(d,u,role){let{data:r}=await d.from('referral_codes').select('*').eq('user_id',u.id).eq('role',role).eq('is_active',true).maybeSingle();if(r)return r;let code=codeFor(role,u.id);const{data:dupe}=await d.from('referral_codes').select('id').eq('code',code).maybeSingle();if(dupe)code=`${code}-${Math.floor(100+Math.random()*900)}`;const{data:newRow,error}=await d.from('referral_codes').insert({user_id:u.id,role,code,is_active:true}).select('*').single();if(error)throw error;return newRow}
export async function GET(req){try{const d=db(),me=await current(req,d),code=await ensureCode(d,me.user,me.role);const[{data:refs},{data:rewards}]=await Promise.all([d.from('referrals').select('*').eq('referrer_user_id',me.user.id).order('created_at',{ascending:false}),d.from('referral_rewards').select('*').eq('beneficiary_user_id',me.user.id).order('granted_at',{ascending:false})]);const referredIds=[...new Set((refs||[]).map(x=>x.referred_user_id).filter(Boolean))];let people={};if(referredIds.length){const[{data:gs},{data:hs}]=await Promise.all([d.from('guests').select('user_id,full_name,phone').in('user_id',referredIds),d.from('host_profiles').select('user_id,full_name,business_name,phone').in('user_id',referredIds)]);people=Object.fromEntries([...(gs||[]).map(x=>[x.user_id,{name:x.full_name,phone:x.phone}]),...(hs||[]).map(x=>[x.user_id,{name:x.business_name||x.full_name,phone:x.phone}])])}return Response.json({success:true,role:me.role,profile:me.profile,code:code.code,shareUrl:`https://nightoutstay.com/ref/${code.code}`,referrals:(refs||[]).map(x=>({...x,referred:people[x.referred_user_id]||null})),rewards:rewards||[],rules:{host_to_host:'15 free subscription days after referred Host uploads a property; maximum 10 qualified Host referrals.',guest_to_guest:'Next booking service charge waived after referred Guest completes a paid booking; maximum 5 qualified Guest referrals.',guest_to_host:'50% off next booking up to ₹1,500 after referred Host uploads a property.'}})}catch(e){return Response.json({success:false,error:e?.message||'Unable to load referrals.'},{status:e?.status||500})}}
export async function POST(req){try{const d=db(),me=await current(req,d),body=await req.json(),code=String(body.code||'').trim().toUpperCase();if(!code)return Response.json({success:false,error:'Referral code is required.'},{status:400});const{data:refCode}=await d.from('referral_codes').select('*').eq('code',code).eq('is_active',true).maybeSingle();if(!refCode)return Response.json({success:false,error:'Referral code is invalid.'},{status:404});if(refCode.user_id===me.user.id)return Response.json({success:false,error:'You cannot use your own referral code.'},{status:400});const{data:existing}=await d.from('referrals').select('id,code,status').eq('referred_user_id',me.user.id).maybeSingle();if(existing)return Response.json({success:true,alreadyClaimed:true,referral:existing});const kind=`${refCode.role}_to_${me.role}`;if(!['host_to_host','guest_to_guest','guest_to_host'].includes(kind))return Response.json({success:false,error:'This referral combination is not eligible for the current program.'},{status:400});const{data:row,error}=await d.from('referrals').insert({code,referrer_user_id:refCode.user_id,referrer_role:refCode.role,referred_user_id:me.user.id,referred_role:me.role,referral_kind:kind,status:'claimed'}).select('*').single();if(error)throw error;return Response.json({success:true,referral:row,message:'Referral code linked successfully. The reward will activate automatically after the qualifying action.'})}catch(e){return Response.json({success:false,error:e?.message||'Unable to apply referral code.'},{status:e?.status||500})}}
