import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL='https://gxwemplbykjxhezefykh.supabase.co';
function adminClient(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.');return createClient(SUPABASE_URL,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function requireHost(request,supabase){const auth=request.headers.get('authorization')||'',token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)throw new Error('UNAUTHORIZED');const {data,error}=await supabase.auth.getUser(token),user=data?.user;if(error||!user)throw new Error('UNAUTHORIZED');const {data:host}=await supabase.from('host_profiles').select('id,user_id,full_name,business_name,status').eq('user_id',user.id).single();if(!host||host.status!=='active')throw new Error('HOST_ACCESS_DENIED');return{host}}
function normalized(p){if(!p)return'not_started';if(p.status==='active'&&p.expires_at&&new Date(p.expires_at)<=new Date())return'expired';return p.status||'not_started'}
export async function GET(request){try{const sb=adminClient(),{host}=await requireHost(request,sb),now=new Date().toISOString();
 await sb.from('property_promotions').update({status:'expired',updated_at:now}).eq('host_id',host.id).eq('status','active').lte('expires_at',now);
 const {data:properties,error:pe}=await sb.from('properties').select('id,name,slug,base_price,is_active,moderation_status,city,area,property_type,created_at').eq('host_id',host.id).order('created_at',{ascending:false});if(pe)throw pe;
 const ids=(properties||[]).map(x=>x.id);let promotions=[];if(ids.length){const {data,error}=await sb.from('property_promotions').select('*').in('property_id',ids).order('created_at',{ascending:false});if(error)throw error;promotions=data||[]}
 const rows=[];for(const property of properties||[]){const history=promotions.filter(x=>x.property_id===property.id),current=history.find(x=>x.status==='active'&&(!x.expires_at||new Date(x.expires_at)>new Date()))||null,pendingApproval=history.find(x=>x.status==='pending_approval')||null,pendingPayment=history.find(x=>x.status==='pending_payment')||null,latest=history[0]||null,relevant=current||pendingApproval||pendingPayment||latest;
  const quotes={};for(const type of ['featured','premium','boosted']){const {data:q,error}=await sb.rpc('get_property_promotion_quote',{p_property_id:property.id,p_promotion_type:type,p_duration_days:30});quotes[type]=error?{error:error.message}:q}
  rows.push({...property,eligible:property.is_active===true&&property.moderation_status==='approved',promotion_status:normalized(relevant),current_promotion:current,pending_approval:pendingApproval,pending_payment:pendingPayment,latest_promotion:latest,promotion_history:history,promotion_quotes:quotes})
 }
 return Response.json({success:true,host,properties:rows})
 }catch(error){const message=error?.message||'Unable to load promotions.',status=message==='UNAUTHORIZED'?401:message==='HOST_ACCESS_DENIED'?403:500;return Response.json({error:message},{status})}}
