import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL='https://gxwemplbykjxhezefykh.supabase.co';
function admin(){ const key=process.env.SUPABASE_SERVICE_ROLE_KEY; if(!key) throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.'); return createClient(SUPABASE_URL,key,{auth:{persistSession:false,autoRefreshToken:false}}); }
function bearer(req){ return String(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim(); }
async function auth(req,portal){ const db=admin(); const token=bearer(req); const {data:u,error:e}=await db.auth.getUser(token); if(e||!u?.user) throw new Error('AUTH'); const user=u.user;
 if(portal==='host'){ const {data:p}=await db.from('host_profiles').select('id,user_id').eq('user_id',user.id).maybeSingle(); if(!p) throw new Error('ACCESS'); return {db,user,profile:p}; }
 if(portal==='guest'){ const {data:p}=await db.from('guests').select('id,user_id').eq('user_id',user.id).maybeSingle(); if(!p) throw new Error('ACCESS'); return {db,user,profile:p}; }
 throw new Error('ACCESS'); }
export async function GET(req){ try{ const portal=new URL(req.url).searchParams.get('portal')||''; const {db,user}=await auth(req,portal); const {data,error}=await db.from('notifications').select('*').eq('recipient_type',portal).eq('recipient_user_id',user.id).order('created_at',{ascending:false}).limit(100); if(error) throw error; return Response.json({success:true,notifications:data||[]}); }catch(e){ return Response.json({success:false,error:e.message==='AUTH'?'Authentication required.':'Unable to load notifications.'},{status:e.message==='AUTH'?401:403}); } }
export async function POST(req){ try{ const body=await req.json(); const portal=String(body.portal||''); const {db,user}=await auth(req,portal); let q=db.from('notifications').update({is_read:true,read_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('recipient_type',portal).eq('recipient_user_id',user.id).eq('is_read',false); if(body.id) q=q.eq('id',body.id); const {error}=await q; if(error) throw error; return Response.json({success:true}); }catch(e){ return Response.json({success:false,error:e.message==='AUTH'?'Authentication required.':'Unable to update notifications.'},{status:e.message==='AUTH'?401:400}); } }
}
