'use client';
import { useEffect,useState } from 'react';
import { createClient } from '@supabase/supabase-js';
const supabase=createClient('https://gxwemplbykjxhezefykh.supabase.co','sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS');
function fmt(v){return v?new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):''}
export default function NotificationsPage(){const portal='guest';const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
async function token(){const {data:{session}}=await supabase.auth.getSession();return session?.access_token||''}
async function load(silent=false){try{if(!silent)setLoading(true);const t=await token();if(!t){location.href='/login';return}const r=await fetch(`/api/portal/notifications?portal=${portal}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Unable to load notifications.');setRows(j.notifications||[]);setError('')}catch(e){setError(e.message)}finally{if(!silent)setLoading(false)}}
async function mark(id){try{const t=await token();await fetch('/api/portal/notifications',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({portal,id})});setRows(old=>old.map(x=>!id||x.id===id?{...x,is_read:true,read_at:new Date().toISOString()}:x))}catch{}}
useEffect(()=>{load();const x=setInterval(()=>load(true),5000);const f=()=>load(true);window.addEventListener('focus',f);return()=>{clearInterval(x);window.removeEventListener('focus',f)}},[]);const unread=rows.filter(x=>!x.is_read).length;return <main className="nt-page"><div className="nt-head"><div><p>GUEST PORTAL</p><h1>Notifications</h1><span>Booking updates, messages, support replies and important account activity.</span></div>{unread>0&&<button onClick={()=>mark('')}>Mark all read</button>}</div>{error&&<div className="nt-error">{error}</div>}{loading?<div className="nt-empty">Loading notifications...</div>:!rows.length?<div className="nt-empty">No notifications yet.</div>:<div className="nt-list">{rows.map(n=><a key={n.id} href={n.action_url||'#'} onClick={()=>mark(n.id)} className={n.is_read?'nt-card':'nt-card unread'}><div className="nt-dot"/><div className="nt-body"><div className="nt-top"><strong>{n.title}</strong><small>{fmt(n.created_at)}</small></div><p>{n.body}</p><span>{String(n.type||'update').replaceAll('_',' ')}</span></div></a>)}</div>}<style jsx global>{`.nt-page{min-height:100vh;background:#f5f7fa;padding:32px clamp(14px,4vw,54px) 70px;font-family:Arial;color:#132238}.nt-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;max-width:1100px;margin:0 auto 20px}.nt-head p{margin:0 0 6px;color:#35618c;font-size:11px;font-weight:900;letter-spacing:1.3px}.nt-head h1{margin:0 0 7px;color:#082f5a;font-size:34px}.nt-head span{color:#667085}.nt-head button{border:1px solid #cbd5e1;background:#fff;border-radius:10px;padding:10px 14px;font-weight:800;color:#082f5a}.nt-list{max-width:1100px;margin:auto;display:grid;gap:10px}.nt-card{display:flex;gap:12px;text-decoration:none;color:inherit;background:#fff;border:1px solid #dbe3ec;border-radius:14px;padding:15px 16px}.nt-card.unread{border-color:#9cc5ec;background:#f7fbff}.nt-dot{width:9px;height:9px;border-radius:50%;background:#cbd5e1;margin-top:6px;flex:0 0 auto}.nt-card.unread .nt-dot{background:#e11d48}.nt-body{min-width:0;flex:1}.nt-top{display:flex;justify-content:space-between;gap:12px}.nt-top strong{color:#082f5a}.nt-top small{color:#667085;white-space:nowrap}.nt-body p{margin:7px 0;color:#475467;line-height:1.45}.nt-body span{font-size:10px;text-transform:uppercase;font-weight:900;color:#667085}.nt-empty,.nt-error{max-width:1100px;margin:auto;background:#fff;border:1px solid #dbe3ec;border-radius:14px;padding:28px;text-align:center;color:#667085}.nt-error{background:#fff1f2;color:#9f1239}@media(max-width:650px){.nt-page{padding:20px 12px 40px}.nt-head{align-items:flex-start;flex-direction:column}.nt-head h1{font-size:28px}.nt-head button{width:100%}.nt-top{flex-direction:column;gap:4px}.nt-card{padding:14px 12px;border-radius:12px}}`}</style></main>}
