import {createClient} from "@supabase/supabase-js";
const URL="https://gxwemplbykjxhezefykh.supabase.co";
function db(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!k)throw new Error("SUPABASE_SERVICE_ROLE_KEY is not configured.");return createClient(URL,k,{auth:{persistSession:false,autoRefreshToken:false}})}
async function admin(req,sb,mode="view"){const h=req.headers.get("authorization")||"",t=h.startsWith("Bearer ")?h.slice(7):"";if(!t)return{error:Response.json({error:"Unauthorized."},{status:401})};const {data}=await sb.auth.getUser(t),u=data?.user;if(!u)return{error:Response.json({error:"Unauthorized."},{status:401})};const {data:a}=await sb.from("admin_profiles").select("user_id,role,is_active,full_access").eq("user_id",u.id).maybeSingle();if(!a?.is_active||!["super_admin","admin"].includes(a.role))return{error:Response.json({error:"Access denied."},{status:403})};if(a.role!=="super_admin"&&!a.full_access){const {data:p}=await sb.from("admin_permissions").select("can_view,can_add,can_edit,can_approve").eq("admin_user_id",u.id).eq("module","promotions").maybeSingle();const ok=mode==="view"?p?.can_view:mode==="add"?p?.can_add:mode==="approve"?p?.can_approve:p?.can_edit;if(!ok)return{error:Response.json({error:"You do not have permission for Promotions."},{status:403})}}return{user:u,profile:a}}
const n=(v,d=0)=>{if(v===""||v==null)return d;const x=Number(v);return Number.isFinite(x)?x:d},nullable=v=>v===""||v==null?null:n(v),start=v=>v?new Date(`${v}T00:00:00.000Z`).toISOString():null,end=v=>v?new Date(`${v}T23:59:59.999Z`).toISOString():null;
export async function GET(req){try{const sb=db(),a=await admin(req,sb);if(a.error)return a.error;const [pr,rr,dr,hr,xr]=await Promise.all([sb.from("property_promotions").select("*").order("created_at",{ascending:false}),sb.from("promotion_pricing_rules").select("*").order("created_at",{ascending:false}),sb.from("host_promotion_discounts").select("*").order("created_at",{ascending:false}),sb.from("host_profiles").select("id,full_name,business_name,email,status").order("business_name"),sb.from("properties").select("id,name,host_id,city,property_type,base_price").order("name")]);for(const r of[pr,rr,dr,hr,xr])if(r.error)throw r.error;const hosts=hr.data||[],properties=xr.data||[],hm=new Map(hosts.map(x=>[x.id,x])),pm=new Map(properties.map(x=>[x.id,x]));
 const promotions=(pr.data||[]).map(x=>({...x,host_name:hm.get(x.host_id)?.full_name,host_business_name:hm.get(x.host_id)?.business_name,property_name:pm.get(x.property_id)?.name}));
 const rules=(rr.data||[]).map(x=>({...x,host_name:hm.get(x.host_id)?.full_name,host_business_name:hm.get(x.host_id)?.business_name,property_name:pm.get(x.property_id)?.name}));
 const discounts=(dr.data||[]).map(x=>({...x,host_name:hm.get(x.host_id)?.full_name,host_business_name:hm.get(x.host_id)?.business_name,property_name:pm.get(x.property_id)?.name}));
 const now=new Date(),active=promotions.filter(x=>x.status==="active"&&(!x.expires_at||new Date(x.expires_at)>now));
 return Response.json({success:true,summary:{active:active.length,pending:promotions.filter(x=>x.status==="pending_approval").length,featured:active.filter(x=>x.promotion_type==="featured").length,premium:active.filter(x=>x.promotion_type==="premium").length,boosted:active.filter(x=>x.promotion_type==="boosted").length,revenue:promotions.filter(x=>x.paid_at).reduce((z,x)=>z+n(x.total_amount),0)},promotions,rules,discounts,hosts,properties});
 }catch(e){console.error(e);return Response.json({error:e.message||"Unable to load promotions."},{status:500})}}
export async function POST(req){try{const sb=db(),b=await req.json(),action=String(b.action||""),mode=["approve","reject","revoke","grant"].includes(action)?"approve":["create_rule","create_discount"].includes(action)?"add":"edit",a=await admin(req,sb,mode);if(a.error)return a.error;
 if(action==="create_rule"){const scopes=["global","city","property_type","city_property_type","host","property"],types=["featured","premium","boosted"],methods=["fixed","subscription_multiplier"];if(!scopes.includes(b.scopeType)||!types.includes(b.promotionType)||!methods.includes(b.pricingMethod))return Response.json({error:"Invalid promotion rule."},{status:400});const city=["city","city_property_type"].includes(b.scopeType)?String(b.city||"").trim():null,pt=["property_type","city_property_type"].includes(b.scopeType)?String(b.propertyType||"").trim():null,host=["host","property"].includes(b.scopeType)?String(b.hostId||"").trim():null,property=b.scopeType==="property"?String(b.propertyId||"").trim():null;if((["city","city_property_type"].includes(b.scopeType)&&!city)||(["property_type","city_property_type"].includes(b.scopeType)&&!pt)||(b.scopeType==="host"&&!host)||(b.scopeType==="property"&&(!host||!property)))return Response.json({error:"Complete all fields required by the selected scope."},{status:400});
  if(property){const {data:p}=await sb.from("properties").select("id").eq("id",property).eq("host_id",host).maybeSingle();if(!p)return Response.json({error:"Selected property does not belong to this Host."},{status:400})}
  const fixed=b.pricingMethod==="fixed"?n(b.fixedFee,-1):null,mult=b.pricingMethod==="subscription_multiplier"?n(b.subscriptionMultiplier,-1):null;if((fixed!==null&&fixed<0)||(mult!==null&&mult<0))return Response.json({error:"Promotion price cannot be negative."},{status:400});
  const {error}=await sb.from("promotion_pricing_rules").insert({rule_name:String(b.ruleName||"").trim(),promotion_type:b.promotionType,scope_type:b.scopeType,city,property_type:pt,host_id:host,property_id:property,pricing_method:b.pricingMethod,fixed_fee:fixed,subscription_multiplier:mult,duration_days:Math.max(1,Math.floor(n(b.durationDays,30))),priority:n(b.priority),valid_from:start(b.validFrom),valid_until:end(b.validUntil),is_active:true,notes:String(b.notes||"").trim()||null,created_by:a.user.id,updated_by:a.user.id});if(error)throw error;return Response.json({success:true,message:"Promotion pricing rule created."})}
 if(action==="toggle_rule"){const {error}=await sb.from("promotion_pricing_rules").update({is_active:Boolean(b.isActive),updated_by:a.user.id,updated_at:new Date().toISOString()}).eq("id",b.id);if(error)throw error;return Response.json({success:true,message:"Pricing rule updated."})}
 if(action==="create_discount"){const host=String(b.hostId||"").trim(),property=String(b.propertyId||"").trim()||null,type=String(b.promotionType||"").trim()||null,dt=String(b.discountType||"percentage");if(!host||!["percentage","fixed","free"].includes(dt)||!["",null,"featured","premium","boosted"].includes(type))return Response.json({error:"Invalid promotion offer."},{status:400});if(property){const {data:p}=await sb.from("properties").select("id").eq("id",property).eq("host_id",host).maybeSingle();if(!p)return Response.json({error:"Selected property does not belong to this Host."},{status:400})}const dv=dt==="free"?0:n(b.discountValue,-1);if(dv<0||(dt==="percentage"&&dv>100))return Response.json({error:"Invalid discount value."},{status:400});const {error}=await sb.from("host_promotion_discounts").insert({host_id:host,property_id:property,promotion_type:type,discount_name:String(b.discountName||"").trim(),discount_type:dt,discount_value:dv,max_discount_amount:dt==="percentage"?nullable(b.maxDiscountAmount):null,valid_from:start(b.validFrom),valid_until:end(b.validUntil),max_uses:b.maxUses===""?null:Math.max(1,Math.floor(n(b.maxUses,1))),is_active:true,reason:String(b.reason||"").trim()||null,created_by:a.user.id,updated_by:a.user.id});if(error)throw error;return Response.json({success:true,message:"Host promotion offer created."})}
 if(action==="toggle_discount"){const {error}=await sb.from("host_promotion_discounts").update({is_active:Boolean(b.isActive),updated_by:a.user.id,updated_at:new Date().toISOString()}).eq("id",b.id);if(error)throw error;return Response.json({success:true,message:"Promotion offer updated."})}
 if(action==="approve"){const now=new Date(),{data:p,error:e}=await sb.from("property_promotions").select("id,status,duration_days").eq("id",b.id).maybeSingle();if(e||!p)return Response.json({error:"Promotion not found."},{status:404});if(p.status!=="pending_approval")return Response.json({error:"Only a pending approval promotion can be approved."},{status:400});const ex=new Date(now);ex.setUTCDate(ex.getUTCDate()+Math.max(1,Number(p.duration_days||30)));const {error}=await sb.from("property_promotions").update({status:"active",approved_at:now.toISOString(),approved_by:a.user.id,starts_at:now.toISOString(),expires_at:ex.toISOString(),updated_at:now.toISOString()}).eq("id",p.id);if(error)throw error;return Response.json({success:true,message:"Promotion approved and activated."})}
 if(action==="reject"){const reason=String(b.reason||"").trim();if(!reason)return Response.json({error:"Rejection reason is required."},{status:400});const {error}=await sb.from("property_promotions").update({status:"rejected",rejected_at:new Date().toISOString(),rejected_by:a.user.id,rejection_reason:reason,updated_at:new Date().toISOString()}).eq("id",b.id).eq("status","pending_approval");if(error)throw error;return Response.json({success:true,message:"Promotion rejected."})}
 if(action==="revoke"){const reason=String(b.reason||"").trim();if(!reason)return Response.json({error:"Revocation reason is required."},{status:400});const now=new Date().toISOString(),{error}=await sb.from("property_promotions").update({status:"cancelled",revoked_at:now,revoked_by:a.user.id,revocation_reason:reason,updated_at:now}).eq("id",b.id).eq("status","active");if(error)throw error;return Response.json({success:true,message:"Promotion revoked."})}
 if(action==="grant"){const host=String(b.hostId||"").trim(),property=String(b.propertyId||"").trim(),type=String(b.promotionType||""),days=Math.max(1,Math.floor(n(b.durationDays,30))),reason=String(b.reason||"").trim();if(!host||!property||!["featured","premium","boosted"].includes(type)||!reason)return Response.json({error:"Host, property, level and reason are required."},{status:400});const {data:p}=await sb.from("properties").select("id,host_id,base_price").eq("id",property).eq("host_id",host).maybeSingle();if(!p)return Response.json({error:"Property does not belong to selected Host."},{status:400});const now=new Date(),ex=new Date(now);ex.setUTCDate(ex.getUTCDate()+days);const {error}=await sb.from("property_promotions").insert({property_id:property,host_id:host,promotion_type:type,plan_months:1,nightly_rate_snapshot:n(p.base_price),subscription_fee_snapshot:0,promotion_fee_before_gst:0,gst_rate:18,gst_amount:0,total_amount:0,status:"active",requested_at:now.toISOString(),approved_at:now.toISOString(),approved_by:a.user.id,starts_at:now.toISOString(),expires_at:ex.toISOString(),duration_days:days,pricing_scope_snapshot:"admin_granted",pricing_rule_name_snapshot:"Complimentary Admin Promotion",pricing_method_snapshot:"complimentary",standard_promotion_fee_snapshot:0,discount_name_snapshot:"Admin Complimentary Promotion",discount_type_snapshot:"free",discount_value_snapshot:0,discount_amount_snapshot:0,pricing_quoted_at:now.toISOString(),admin_granted:true,revocation_reason:null});if(error)throw error;return Response.json({success:true,message:"Complimentary promotion activated."})}
 return Response.json({error:"Unknown promotion action."},{status:400});
 }catch(e){console.error(e);return Response.json({error:e.message||"Unable to update promotions."},{status:500})}}
