'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { usePathname,useRouter } from 'next/navigation';
import { createClient } from '@supabase/supabase-js';
const supabase=createClient('https://gxwemplbykjxhezefykh.supabase.co','sb_publishable_MOsISosc6eV2rfgn-fUVoA_KmrmYLqS');
const ITEMS=[
{label:'Dashboard',href:'/host',icon:'⌂',key:''},{label:'My Properties',href:'/host/properties',icon:'▥',key:''},{label:'Bookings',href:'/host/bookings',icon:'▣',key:'bookings'},{label:'Calendar',href:'/host/calendar',icon:'▦',key:''},{label:'Messages',href:'/host/messages',icon:'▭',key:'messages'},{label:'Notifications',href:'/host/notifications',icon:'◈',key:'notifications'},{label:'Offers',href:'/host/offers',icon:'◇',key:''},{label:'Reviews',href:'/host/reviews',icon:'★',key:''},{label:'Subscription',href:'/host/subscription',icon:'▤',key:''},{label:'Promotions',href:'/host/promotions',icon:'◆',key:''},{label:'Referrals',href:'/host/referrals',icon:'⇄',key:''},{label:'Payouts',href:'/host/payouts',icon:'▰',key:''},{label:'Reports',href:'/host/reports',icon:'▧',key:''},{label:'Support',href:'/host/help',icon:'?',key:''},{label:'Profile',href:'/host/profile',icon:'♙',key:''}];
export default function HostNav({host}){const pathname=usePathname();const router=useRouter();const [counts,setCounts]=useState({messages:0,notifications:0,bookings:0});
useEffect(()=>{let live=true,timer;async function load(){try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return;const r=await fetch('/api/portal/summary?portal=host',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const j=await r.json();if(live&&j.success)setCounts(j)}catch{}}const refresh=()=>{clearTimeout(timer);timer=setTimeout(load,180)};load();const ch=supabase.channel('host-nav-live').on('postgres_changes',{event:'*',schema:'public',table:'booking_messages'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'bookings'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'notifications'},refresh).subscribe();const t=setInterval(load,45000);const vis=()=>{if(document.visibilityState==='visible')load()};window.addEventListener('focus',load);document.addEventListener('visibilitychange',vis);return()=>{live=false;clearTimeout(timer);clearInterval(t);window.removeEventListener('focus',load);document.removeEventListener('visibilitychange',vis);supabase.removeChannel(ch)}},[]);
const active=h=>h==='/host'?pathname==='/host':pathname===h||pathname?.startsWith(`${h}/`);async function logout(){await supabase.auth.signOut();router.replace('/login');router.refresh()}const hostName=host?.business_name||host?.full_name||'Host';const hostPerson=host?.full_name&&host?.business_name&&host.full_name!==host.business_name?host.full_name:'Host Account';return <><div className="portalNavRoot"><div className="portalMobileBrand"><strong>NightOutStays</strong><span>Host Portal</span></div><div className="portalMenuRow"><div className="portalMenuGrid">{ITEMS.map(i=>{const n=Number(counts[i.key]||0);return <Link key={i.href} href={i.href} className={active(i.href)?'portalItem active':'portalItem'}><span className="portalIconWrap"><span className="portalIcon">{i.icon}</span>{n>0&&<span className="portalBadge">{n>99?'99+':n}</span>}</span><span className="portalLabel">{i.label}</span></Link>})}</div></div><div className="portalDetails"><div className="portalIdentity"><span className="portalRole">HOST</span><div className="portalWho"><strong>{hostName}</strong><span>{hostPerson}</span></div></div><div className="portalActions"><Link href="/" target="_blank" className="portalBtn">↗ View Website</Link><button className="portalBtn" onClick={logout}>Logout</button></div></div></div><Styles/></>}
function Styles(){return <style jsx global>{`
      .portalNavRoot,.portalNavRoot *{box-sizing:border-box}.portalNavRoot{width:100%;background:#fff;border-bottom:1px solid #dfe5ec;position:relative;z-index:1000;font-family:Arial,sans-serif}.portalMenuRow{background:#303a44;width:100%}.portalMenuGrid{display:flex;width:100%;background:#303a44;overflow:hidden}.portalItem{position:relative;flex:1 1 0;min-width:0;min-height:68px;padding:8px 4px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;color:#fff!important;text-decoration:none!important}.portalItem:hover{background:rgba(255,255,255,.08)}.portalItem.active{background:#4a5560}.portalItem.active:after{content:'';position:absolute;left:22%;right:22%;bottom:0;height:4px;border-radius:4px 4px 0 0;background:#f00078}.portalIconWrap{position:relative;display:inline-flex;align-items:center;justify-content:center}.portalIcon{font-size:16px;line-height:1}.portalBadge{position:absolute;top:-9px;right:-13px;min-width:18px;height:18px;padding:0 5px;border-radius:999px;background:#e11d48;color:#fff;font-size:10px;font-weight:900;display:inline-flex;align-items:center;justify-content:center;border:2px solid #303a44}.portalLabel{font-size:9px;line-height:1.1;text-align:center;font-weight:900}.portalDetails{min-height:58px;display:flex;align-items:center;justify-content:space-between;gap:16px;width:calc(100% - 48px);max-width:1500px;margin:0 auto}.portalIdentity{display:flex;align-items:center;gap:12px;min-width:0}.portalRole{background:#f00078;color:#fff;border-radius:999px;padding:6px 10px;font-size:9px;font-weight:900;letter-spacing:.5px;white-space:nowrap}.portalWho{display:flex;flex-direction:column;min-width:0}.portalWho strong{font-size:13px;color:#101828;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.portalWho span{font-size:10px;color:#667085;margin-top:2px}.portalActions{display:flex;gap:8px}.portalBtn{min-height:34px;padding:0 12px;border:1px solid #ccd6e1;border-radius:8px;background:#fff;color:#303a44;text-decoration:none;font-size:10px;font-weight:900;display:inline-flex;align-items:center;justify-content:center;cursor:pointer}.portalMobileBrand{display:none}.portalScrollHint{display:none}
      @media(max-width:900px){.portalMenuGrid{display:flex!important;overflow-x:auto;overflow-y:hidden;scrollbar-width:none;-webkit-overflow-scrolling:touch;scroll-snap-type:x proximity}.portalMenuGrid::-webkit-scrollbar{display:none}.portalItem{flex:0 0 88px;min-height:62px;scroll-snap-align:start}.portalDetails{width:calc(100% - 24px);min-height:54px}.portalLabel{font-size:8.5px}.portalScrollHint{display:block;position:absolute;right:5px;top:21px;color:rgba(255,255,255,.65);font-size:11px;pointer-events:none}.portalActions .portalBtn:first-child{display:none}}
      @media(max-width:560px){.portalNavRoot{position:sticky;top:0}.portalMobileBrand{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;background:#fff}.portalMobileBrand strong{font-size:20px;color:#303a44}.portalMobileBrand span{font-size:10px;color:#667085;font-weight:800}.portalDetails{padding:7px 0;min-height:48px}.portalWho strong{font-size:12px}.portalWho span{font-size:9px}.portalRole{font-size:8px;padding:5px 8px}.portalBtn{min-height:32px;padding:0 10px;font-size:9px}.portalItem{flex-basis:76px;min-height:58px}.portalIcon{font-size:15px}.portalLabel{font-size:8px}.portalBadge{top:-8px;right:-12px;min-width:17px;height:17px;font-size:9px}.portalMenuRow{box-shadow:0 2px 10px rgba(48,58,68,.12)}}
`}</style>}
