import {createClient} from '@supabase/supabase-js';
const SUPABASE_URL='https://gxwemplbykjxhezefykh.supabase.co';
function db(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!k)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.');return createClient(SUPABASE_URL,k,{auth:{persistSession:false,autoRefreshToken:false}})}
async function admin(req,d){const t=String(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();const{data:u}=await d.auth.getUser(t);if(!u?.user)throw Object.assign(new Error('Admin login required.'),{status:401});const{data:a}=await d.from('admin_profiles').select('is_active').eq('user_id',u.user.id).maybeSingle();if(!a?.is_active)throw Object.assign(new Error('Admin access required.'),{status:403})}
const val=v=>v??''; const inRange=(v,from,to)=>{if(!v)return true;const x=String(v).slice(0,10);return(!from||x>=from)&&(!to||x<=to)};
export async function GET(req){try{const d=db();await admin(req,d);const u=new URL(req.url),dataset=(u.searchParams.get('dataset')||'bookings').toLowerCase(),from=u.searchParams.get('from')||'',to=u.searchParams.get('to')||'',propertyId=u.searchParams.get('propertyId')||'',hostId=u.searchParams.get('hostId')||'';
const[{data:hosts},{data:guests},{data:props}]=await Promise.all([d.from('host_profiles').select('id,user_id,full_name,business_name,phone,email,status,created_at'),d.from('guests').select('id,user_id,full_name,phone,email,status,created_at'),d.from('properties').select('id,host_id,name,city,location_name,property_type,base_price,max_guests,moderation_status,is_active,created_at')]);const H=Object.fromEntries((hosts||[]).map(x=>[x.id,x])),G=Object.fromEntries((guests||[]).map(x=>[x.id,x])),P=Object.fromEntries((props||[]).map(x=>[x.id,x]));let rows=[],title='Report';
if(dataset==='properties'){title='Property Data';rows=(props||[]).filter(x=>(!hostId||x.host_id===hostId)&&inRange(x.created_at,from,to)).map(x=>({'Property':x.name,'Host':H[x.host_id]?.business_name||H[x.host_id]?.full_name,'City':x.city,'Location':x.location_name,'Type':x.property_type,'Rate':x.base_price,'Max Guests':x.max_guests,'Status':x.moderation_status,'Active':x.is_active?'Yes':'No','Created':x.created_at}))}
else if(dataset==='hosts'){title='Host Data';rows=(hosts||[]).filter(x=>(!hostId||x.id===hostId)&&inRange(x.created_at,from,to)).map(x=>({'Host':x.business_name||x.full_name,'Contact Name':x.full_name,'Phone':x.phone,'Email':x.email,'Status':x.status,'Properties':(props||[]).filter(p=>p.host_id===x.id).length,'Created':x.created_at}))}
else if(dataset==='guests'){title='Guest Data';rows=(guests||[]).filter(x=>inRange(x.created_at,from,to)).map(x=>({'Guest':x.full_name,'Phone':x.phone,'Email':x.email,'Status':x.status,'Created':x.created_at}))}
else if(['bookings','portal-fees'].includes(dataset)){title=dataset==='portal-fees'?'Guest Portal Fees':'Booking Data';const{data:b,error}=await d.from('bookings').select('*').order('created_at',{ascending:false});if(error)throw error;rows=(b||[]).filter(x=>(!propertyId||x.property_id===propertyId)&&(!hostId||P[x.property_id]?.host_id===hostId)&&inRange(x.created_at,from,to)).map(x=>({'Booking':x.booking_code,'Property':P[x.property_id]?.name,'Host':H[P[x.property_id]?.host_id]?.business_name||H[P[x.property_id]?.host_id]?.full_name,'Guest':G[x.guest_id]?.full_name,'Check In':x.check_in,'Check Out':x.check_out,'Nights':x.nights,'Accommodation':x.taxable_amount,'Accommodation GST':x.accommodation_gst||x.gst_amount,'Portal Fee incl GST':x.portal_fee||x.service_charge,'Referral Discount':x.referral_discount_amount,'Final Payable':x.final_payable_amount,'Payment':x.payment_status,'Paid At':x.paid_at,'Created':x.created_at}));if(dataset==='portal-fees')rows=rows.filter(x=>Number(x['Portal Fee incl GST']||0)>0)}
else if(dataset==='referrals'||dataset==='referral-discounts'){title=dataset==='referrals'?'Referral Data':'Referral Discounts';if(dataset==='referrals'){const{data:r,error}=await d.from('referrals').select('*').order('created_at',{ascending:false});if(error)throw error;const people={};for(const x of guests||[])people[x.user_id]={name:x.full_name,phone:x.phone};for(const x of hosts||[])people[x.user_id]={name:x.business_name||x.full_name,phone:x.phone};rows=(r||[]).filter(x=>inRange(x.created_at,from,to)).map(x=>({'Code':x.code,'Referrer':people[x.referrer_user_id]?.name,'Referrer Phone':people[x.referrer_user_id]?.phone,'Referrer Role':x.referrer_role,'Referred':people[x.referred_user_id]?.name,'Referred Phone':people[x.referred_user_id]?.phone,'Type':x.referral_kind,'Status':x.status,'Qualified':x.qualified_at,'Created':x.created_at}))}else{const{data:r,error}=await d.from('referral_rewards').select('*').order('granted_at',{ascending:false});if(error)throw error;rows=(r||[]).filter(x=>inRange(x.granted_at,from,to)).map(x=>({'Beneficiary Role':x.beneficiary_role,'Reward Type':x.reward_type,'Percent':x.percent_value,'Max Amount':x.max_amount,'Days':x.days_value,'Status':x.status,'Booking':x.applied_booking_id,'Subscription':x.applied_subscription_id,'Granted':x.granted_at,'Used':x.used_at}))}}
else if(dataset==='subscriptions'){title='Monthly Host Subscriptions';const{data:s,error}=await d.from('property_subscriptions').select('*').order('created_at',{ascending:false});if(error)throw error;rows=(s||[]).filter(x=>(!hostId||x.host_id===hostId)&&inRange(x.created_at,from,to)).map(x=>({'Host':H[x.host_id]?.business_name||H[x.host_id]?.full_name,'Property':P[x.property_id]?.name,'Months':x.plan_months,'Fee Before GST':x.fee_before_gst,'GST':x.gst_amount,'Total':x.total_amount,'Status':x.status,'Paid At':x.paid_at,'Starts':x.starts_at,'Expires':x.expires_at,'Created':x.created_at}))}
else if(['payouts','payment-holds'].includes(dataset)){title=dataset==='payouts'?'Payout Data':'Payment Hold Data';let q=d.from('host_settlements').select('*').order('created_at',{ascending:false});if(dataset==='payment-holds')q=q.eq('is_on_hold',true);const{data:s,error}=await q;if(error)throw error;rows=(s||[]).filter(x=>(!propertyId||x.property_id===propertyId)&&(!hostId||x.host_id===hostId)&&inRange(x.created_at,from,to)).map(x=>({'Property':P[x.property_id]?.name,'Host':H[x.host_id]?.business_name||H[x.host_id]?.full_name,'Guest Paid':x.guest_paid_amount,'Host Gross':x.host_gross_amount,'Deductions':x.total_host_deductions,'Net Payout':x.net_host_payout,'Status':x.payout_status,'On Hold':x.is_on_hold?'Yes':'No','Hold Reason':x.hold_reason,'Created':x.created_at}))}
else throw Object.assign(new Error('Unsupported report.'),{status:400});return Response.json({success:true,title,dataset,rows,filters:{from,to,propertyId,hostId}})}catch(e){return Response.json({success:false,error:e?.message||'Unable to generate report.'},{status:e?.status||500})}}
