import {createClient} from '@supabase/supabase-js';
const URL='https://gxwemplbykjxhezefykh.supabase.co';
function db(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!k)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.');return createClient(URL,k,{auth:{persistSession:false,autoRefreshToken:false}})}
async function requireAdmin(req,d){const t=String(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!t)throw Object.assign(new Error('Authentication required.'),{status:401});const{data:u,error}=await d.auth.getUser(t);if(error||!u?.user)throw Object.assign(new Error('Invalid login session.'),{status:401});const{data:a}=await d.from('admin_profiles').select('user_id,role,is_active,full_access').eq('user_id',u.user.id).maybeSingle();if(!a?.is_active)throw Object.assign(new Error('Admin access required.'),{status:403});return a}
const pick=(o,keys)=>Object.fromEntries(keys.map(k=>[k,o?.[k]??'']));
async function maps(d){const[{data:hosts},{data:guests},{data:props}]=await Promise.all([d.from('host_profiles').select('id,user_id,full_name,business_name,phone,email,city,state,status,identity_verification_status,created_at'),d.from('guests').select('id,user_id,full_name,phone,email,status,verification_status,identity_verification_status,created_at'),d.from('properties').select('*')]);return{hosts:hosts||[],guests:guests||[],props:props||[],h:Object.fromEntries((hosts||[]).map(x=>[x.id,x])),g:Object.fromEntries((guests||[]).map(x=>[x.id,x])),p:Object.fromEntries((props||[]).map(x=>[x.id,x]))}}
export async function GET(req){try{const d=db();await requireAdmin(req,d);const dataset=String(new URL(req.url).searchParams.get('dataset')||'bookings').toLowerCase();const m=await maps(d);let rows=[],title='Report';
if(dataset==='properties'){title='Property Data';rows=m.props.map(x=>{const h=m.h[x.host_id]||{};return{'Property Name':x.name||'','Host Name':h.business_name||h.full_name||'','Host Phone':h.phone||'','Host Email':h.email||'','City':x.city||'','Location':x.location_name||x.area||'','Property Type':x.property_type||x.type||'','Base Price':x.base_price||x.base_rate||'','Max Guests':x.max_guests||'','Moderation':x.moderation_status||'','Active':x.is_active===true?'Yes':'No','Created At':x.created_at||''}})}
else if(dataset==='hosts'){title='Host Data';rows=m.hosts.map(x=>({...pick(x,['full_name','business_name','phone','email','city','state','status','identity_verification_status','created_at']),'Property Count':m.props.filter(p=>p.host_id===x.id).length}))}
else if(dataset==='guests'){title='Guest Data';rows=m.guests.map(x=>pick(x,['full_name','phone','email','status','identity_verification_status','created_at']))}
else if(dataset==='bookings'){title='Booking Data';const{data:b,error}=await d.from('bookings').select('*').order('created_at',{ascending:false});if(error)throw error;rows=(b||[]).map(x=>{const p=m.p[x.property_id]||{},h=m.h[p.host_id]||{},g=m.g[x.guest_id]||{};return{'Booking Code':x.booking_code||'','Property':p.name||'','Host':h.business_name||h.full_name||'','Host Phone':h.phone||'','Guest':g.full_name||'','Guest Phone':g.phone||'','Check In':x.check_in||'','Check Out':x.check_out||'','Guests':x.guests_count||'','Nights':x.nights||'','Booking Status':x.booking_status||'','Host Decision':x.host_decision||'','Payment Status':x.payment_status||'','Payment Due':x.payment_due_at||'','Amount':x.final_payable_amount||x.amount_including_gst||x.total_amount||'','Paid At':x.paid_at||'','Created At':x.created_at||''}})}
else if(dataset==='payouts'||dataset==='payment-holds'){title=dataset==='payouts'?'Payout Data':'Payment Hold Data';let q=d.from('host_settlements').select('*').order('created_at',{ascending:false});if(dataset==='payment-holds')q=q.eq('is_on_hold',true);const{data:s,error}=await q;if(error)throw error;rows=(s||[]).map(x=>{const p=m.p[x.property_id]||{},h=m.h[x.host_id]||{};return{'Booking ID':x.booking_id||'','Property':p.name||'','Host':h.business_name||h.full_name||'','Host Phone':h.phone||'','Guest Paid':x.guest_paid_amount||'','Host Gross':x.host_gross_amount||'','Total Deductions':x.total_host_deductions||'','Net Payout':x.net_host_payout||'','Payout Status':x.payout_status||'','On Hold':x.is_on_hold?'Yes':'No','Hold Reason':x.hold_reason||'','Eligible At':x.eligible_at||'','Transfer ID':x.razorpay_transfer_id||'','Created At':x.created_at||''}})}
else if(dataset==='referrals'){title='Referral Data';const{data:r,error}=await d.from('referrals').select('*').order('created_at',{ascending:false});if(error)throw error;const ids=[...new Set((r||[]).flatMap(x=>[x.referrer_user_id,x.referred_user_id]).filter(Boolean))];const people={};if(ids.length){const[{data:gs},{data:hs}]=await Promise.all([d.from('guests').select('user_id,full_name,phone').in('user_id',ids),d.from('host_profiles').select('user_id,full_name,business_name,phone').in('user_id',ids)]);for(const x of gs||[])people[x.user_id]={name:x.full_name,phone:x.phone};for(const x of hs||[])people[x.user_id]={name:x.business_name||x.full_name,phone:x.phone}}rows=(r||[]).map(x=>({'Referral Code':x.code||'','Referrer':people[x.referrer_user_id]?.name||'','Referrer Phone':people[x.referrer_user_id]?.phone||'','Referrer Role':x.referrer_role||'','Referred':people[x.referred_user_id]?.name||'','Referred Phone':people[x.referred_user_id]?.phone||'','Referred Role':x.referred_role||'','Referral Type':x.referral_kind||'','Status':x.status||'','Qualified At':x.qualified_at||'','Created At':x.created_at||''}))}
else return Response.json({success:false,error:'Unsupported report.'},{status:400});return Response.json({success:true,dataset,title,generatedAt:new Date().toISOString(),rows})}catch(e){return Response.json({success:false,error:e?.message||'Unable to generate report.'},{status:e?.status||500})}}
